package main

// rsyncExcludes is the canonical list of paths to exclude when copying the
// Magento httpdocs directory to staging. These are regenerable caches, logs,
// media caches, and large-but-disposable directories.
//
// Order matters only for readability; rsync applies all --exclude patterns.
var rsyncExcludes = []string{
	// Magento var/
	"var/cache/*",
	"var/page_cache/*",
	"var/session/*",
	"var/log/*",
	"var/report/*",
	"var/tmp/*",
	"var/export/*",
	"var/feeder/*",
	"var/website_cache/*",
	"var/view_preprocessed/*",
	"var/import/*",
	"var/importexport/*",
	"var/import_history/*",
	"var/composer_home/*",
	"var/backups/*",

	// Plesk / Imunify connector
	"connector/*",

	// Magento generated code & DI
	"generated/*",

	// Static assets (regenerated by setup:upgrade / deploy:static:content)
	// Keep .htaccess (has rewrite rule for versioned URLs) but skip generated content
	"pub/static/frontend/*",
	"pub/static/adminhtml/*",
	"pub/static/_requirejs/*",
	"pub/static/deployed_version.txt",

	// Media caches and import staging areas
	"pub/media/cache/*",
	"pub/media/tmp/*",
	"pub/media/analytics/*",
	"pub/media/import/*",
	"pub/media/.thumbs*/",
	"pub/media/catalog/product/cache/*",
	"pub/media/catalog/product/cache.old/*",

	// Sitemaps (regenerated by cron)
	"pub/sitemap-*.xml",
	"pub/sitemap.xml",

	// Misc log/output files
	"nohup.out",
	"output.log",
	"error_log",

	// Git history (large, not needed in staging)
	".git/",
}

// schemaOnlyTables is the canonical list of Magento tables whose DATA is
// skipped during mysqldump (only CREATE TABLE statements are emitted).
//
// Categories:
//   * Indexer changelogs (_cl), replicas (_replica), temp (_tmp)
//   * Sales aggregates (regenerated by cron/reindex)
//   * Search history (regenerated by users)
//   * Logs / cache / sessions (regenerated)
//   * Security tokens (oauth, vault, integration) - never leak to staging
//   * Payment transactions (eurobank, paypal) - never leak to staging
//   * Admin UI state (ui_bookmark, admin_passwords, admin_user_session)
//   * Customer grid flat (regenerated by indexer)
//   * Reporting tables (regenerated)
//   * Message queues (queue_*, magento_bulk, magento_operation)
//   * Import/export history (amasty_import_process, amasty_export_process)
//
// Pattern-based matching: any table name matching these patterns is treated
// as schema-only. The pattern is a glob match against the table name
// (case-insensitive, MySQL stores table names case-sensitively on Linux but
// we match both cases defensively).
var schemaOnlyPatterns = []string{
	// Indexer changelogs / replicas / temp
	"%_cl",
	"%_replica",
	"%_tmp",

	// Sales aggregates (regenerable)
	"sales_bestsellers_aggregated_%",
	"salesrule_coupon_aggregated%",
	"sales_order_aggregated_%",
	"sales_invoiced_aggregated%",
	"sales_refunded_aggregated%",
	"sales_shipping_aggregated%",
	"tax_order_aggregated_%",

	// Reporting
	"reporting_%",
	"report_viewed_product_aggregated_%",
	"report_event",
	"report_compared_product_index",

	// Search history
	"search_query",
	"amasty_xsearch_users_search",

	// Logs
	"cron_schedule",
	"customer_log",
	"customer_visitor",
	"log_visitor",
	"log_visitor_info",
	"log_url",
	"log_url_info",
	"log_customer",
	"log_quote",
	"adminnotification_inbox",
	"admin_system_messages",
	"admin_analytics_usage_version_log",
	"admin_passwords",
	"admin_user_session",
	"admin_user_expiration",
	"release_notification_viewer_log",
	"magento_admin_notifications",
	"magento_login_as_customer_log",
	"login_as_customer",
	"login_as_customer_assistance_allowed",
	"rating_option_vote_aggregated",

	// Cache / sessions
	"cache",
	"cache_tag",
	"session",

	// Security tokens
	"oauth_token",
	"oauth_token_request_log",
	"oauth_nonce",
	"oauth_consumer",
	"integration",
	"integration_config",
	"integration_config_set",
	"vault_payment_token",
	"vault_payment_token_order_payment_link",
	"jwt_auth_revoked",

	// Payment transactions
	"payment_transaction",
	"paypal_payment_transaction",
	"eurobank_transactions",
	"signifyd_case",

	// Admin UI state
	"ui_bookmark",

	// Customer grid flat (regenerated)
	"customer_grid_flat",

	// Catalog flat indexes (regenerated by indexer)
	"catalog_product_flat_%",
	"catalog_category_flat_%",

	// Catalogsearch index (regenerated by indexer)
	"catalogsearch_fulltext_%",
	"catalogsearch_recommendations",

	// Message queues
	"queue",
	"queue_lock",
	"queue_message",
	"queue_message_status",
	"queue_poison_pill",
	"magento_bulk",
	"magento_operation",
	"magento_acknowledgement",
	"magento_acknowledgement_bulk",
	"magento_repair_staging",

	// Mostviewed analytics temp
	"mostviewed_view_temp",
	"mostviewed_click_temp",
	"mostviewed_analytics",

	// Amasty import/export history
	"amasty_import_process",
	"amasty_import_history",
	"amasty_import_batch",
	"amasty_import_file_upload_map",
	"amasty_import_cron_job",
	"amasty_export_process",
	"amasty_export_history",
	"amasty_export_cron_job",
	"amasty_export_last_exported_id",
	"amasty_pgrid_qty_sold",
	"amasty_pgrid_qty_sold_cl",

	// Yotpo / Weltpixel state
	"yotpo_sync",
	"yotpo_rich_snippets",
	"yotpo_order_status_history",
	"weltpixel_license",
}

// salesSchemaOnlyPatterns lists tables whose DATA is skipped when the user
// passes --no-sales-data. Only the structure (CREATE TABLE) is copied.
//
// Includes:
//   * sales_order* + grid + address + payment + status_history + tax
//   * sales_invoice* + grid + item + comment
//   * sales_shipment* + grid + item + track + comment
//   * sales_creditmemo* + grid + item + comment
//   * sales_payment_transaction
//   * salesrule* (cart price rules + coupons + aggregated stats)
//   * sales_*_aggregated* (regenerable reports)
//   * sequence_order_*, sequence_invoice_*, sequence_shipment_*, sequence_creditmemo_*
//   * quote*, quote_id_mask (active carts)
//   * magento_rma* (returns)
//   * paypal_billing_agreement*
//   * amasty_order_* (Amasty order attributes)
//   * amasty_amcheckout_* (Amasty checkout additional data)
//   * amasty_conditions_quote
//   * amasty_cash_on_delivery_fee_quote
//   * eurobank_transactions (already in main list but kept for safety)
//   * inventory_reservation (reservations tied to orders)
//   * inventory_source_item (per-source stock - tied to sales)
//   * gift_message (order gift messages)
//
// NOTE: cataloginventory_stock_item / cataloginventory_stock_status are KEPT
// because they reflect current product stock levels, not order history.
var salesSchemaOnlyPatterns = []string{
	"sales_order%",
	"sales_invoice%",
	"sales_shipment%",
	"sales_creditmemo%",
	"sales_payment_transaction",
	"sales_invoiced_aggregated%",
	"sales_shipping_aggregated%",
	"sales_refunded_aggregated%",
	"salesrule%",
	"sales_%_aggregated%",
	"sequence_order%",
	"sequence_invoice%",
	"sequence_shipment%",
	"sequence_creditmemo%",
	"quote%",
	"magento_rma%",
	"magento_salesrule%",
	"paypal_billing_agreement%",
	"amasty_order%",
	"amasty_amcheckout_additional",
	"amasty_amcheckout_quote_passwords",
	"amasty_amcheckout_order_custom_fields",
	"amasty_conditions_quote",
	"amasty_cash_on_delivery_fee_quote",
	"amasty_table_rate_replica",
	"gift_message",
	"inventory_reservation",
	"inventory_source_item",
}

// customerSchemaOnlyPatterns lists tables whose DATA is skipped when the user
// passes --no-customer-data. Only the structure is copied.
//
// Includes:
//   * customer_entity* (all EAV: varchar/int/decimal/datetime/text)
//   * customer_address_entity* (all EAV)
//   * customer_grid_flat (regenerable from customer_entity)
//   * customer_log, customer_visitor
//   * customer_dummy_cl (indexer changelog)
//   * newsletter_subscriber, newsletter_queue*, newsletter_template*
//   * review%, rating% (product reviews)
//   * wishlist, wishlist_item*
//   * email_% (email marketing automation data)
//   * oauth_token (tied to customer/admin sessions)
//   * vault_payment_token (saved customer payment methods)
//   * magento_login_as_customer% (login-as-customer log)
var customerSchemaOnlyPatterns = []string{
	"customer_entity%",
	"customer_address_entity%",
	"customer_grid_flat",
	"customer_log",
	"customer_visitor",
	"customer_dummy_cl",
	"newsletter_subscriber",
	"newsletter_queue%",
	"newsletter_template%",
	"review%",
	"rating%",
	"wishlist%",
	"email_%",
	"oauth_token",
	"vault_payment_token",
	"vault_payment_token_order_payment_link",
	"login_as_customer%",
	"magento_login_as_customer%",
	"magespam_%",
	"msp_tfa_user_config",
	"msp_tfa_trusted",
}
